version: "3.8"

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_LOCAL_PORT}"
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
